// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuBiRoLDPNNcP9rBAS5iIhCe5CVjJHri4',
    appId: '1:229997766723:web:5133a68b5e6c68887b0cf6',
    messagingSenderId: '229997766723',
    projectId: 'assignment1-1e20c',
    authDomain: 'assignment1-1e20c.firebaseapp.com',
    storageBucket: 'assignment1-1e20c.appspot.com',
    measurementId: 'G-9HQTQQCQ0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9qiiWvWmS5f8kXa1tmmR2UKMlhZ9gP9k',
    appId: '1:229997766723:android:c0be235c730e79557b0cf6',
    messagingSenderId: '229997766723',
    projectId: 'assignment1-1e20c',
    storageBucket: 'assignment1-1e20c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPEVNhkWgFLCVlfyucltvUFuoNocrmcng',
    appId: '1:229997766723:ios:a882b203e880ee777b0cf6',
    messagingSenderId: '229997766723',
    projectId: 'assignment1-1e20c',
    storageBucket: 'assignment1-1e20c.appspot.com',
    iosBundleId: 'com.example.assignment1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPEVNhkWgFLCVlfyucltvUFuoNocrmcng',
    appId: '1:229997766723:ios:a882b203e880ee777b0cf6',
    messagingSenderId: '229997766723',
    projectId: 'assignment1-1e20c',
    storageBucket: 'assignment1-1e20c.appspot.com',
    iosBundleId: 'com.example.assignment1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuBiRoLDPNNcP9rBAS5iIhCe5CVjJHri4',
    appId: '1:229997766723:web:9234fdaae059c2427b0cf6',
    messagingSenderId: '229997766723',
    projectId: 'assignment1-1e20c',
    authDomain: 'assignment1-1e20c.firebaseapp.com',
    storageBucket: 'assignment1-1e20c.appspot.com',
    measurementId: 'G-PH45902049',
  );

}